name: Pull Request CI
run-name: ${{ github.actor }} created/updated a pull request 🚀
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  Pull-Request-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out ${{ github.repository }}...
        uses: actions/checkout@v3
      - name: Setting up PHP environment...
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: pcntl, sysvmsg, sysvsem, sysvshm, intl
        env:
          fail-fast: true
      - name: Cleaning previous build...
        run: make clean
      - name: Installing ${{ github.repository }}...
        run: make install
      - name: Checking Code Style
        run: make phpcs
      - name: Running Static Analyze
        run: make phpstan
      - name: Running Unit Tests
        run: make tests
      - name: Test PHP 8.1 compatibility
        run: make php81compatibility
      - name: Test PHP 8.2 compatibility
        run: make php82compatibility
  Deployment-Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Create SSH context
        run: |
          mkdir ~/.ssh && touch ~/.ssh/known_hosts 
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa 
          ssh-keyscan -p ${{ secrets.DEPLOY_SSH_PORT }} -H ${{ secrets.DEPLOY_SSH_HOST }} > ~/.ssh/known_hosts && chmod 700 ~/.ssh/known_hosts
      - name: SSH connect
        run: |
          ssh ${{ secrets.DEPLOY_SSH_USER }}@${{ secrets.DEPLOY_SSH_HOST }} -p ${{ secrets.DEPLOY_SSH_PORT }} "touch sometestfile.txt"
      - name: Clear everything
        run: rm -rf ~/.ssh
      - name: List everything
        run: |
          ls -lah ~
          ls -lah ~/.ssh
