name: Pull Request CI
run-name: ${{ github.actor }} created a pull request 🚀
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  Pull-Request-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out ${{ github.repository }}...
        uses: actions/checkout@v3
      - name: Setting up PHP environment...
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: pcntl, sysvmsg, sysvsem, sysvshm, intl
        env:
          fail-fast: true
      - name: Cleaning previous build...
        run: make clean
      - name: Installing ${{ github.repository }}...
        run: make install
      - name: Checking Code Style
        run: make phpcs
      - name: Running Static Analyze
        run: make phpstan
      - name: Running Unit Tests
        run: make tests
      - name: Test PHP 8.1 compatibility
        run: make php81compatibility
      - name: Test PHP 8.2 compatibility
        run: make php82compatibility
  Hello-World-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World Action Step
        id: hello
        uses: antoine1302/ssh-deploy@v1.0.0
        with:
          who-to-greet: 'Totoro1302'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
